"""
KMS-based encryption for production environments.

Uses AWS KMS (Key Management Service) for secure key storage and management.
This ensures:
- Keys never stored in application code or .env files
- Only authorized services can decrypt data
- Full audit trail of key usage
- Automatic key rotation
- Hardware Security Module (HSM) backed keys

Setup Requirements:
1. AWS Account with KMS enabled
2. IAM Role for ECS/EC2 instances with kms:Decrypt permission
3. KMS Key created in AWS Console
4. Set KMS_KEY_ID environment variable

For development, encryption is disabled (plaintext storage).
For production (AWS deployment), KMS encryption is enabled.
"""

import os
import base64
from typing import Optional, Tuple

# Try to import boto3 (AWS SDK)
try:
    import boto3
    from botocore.exceptions import ClientError
    KMS_AVAILABLE = True
except ImportError:
    KMS_AVAILABLE = False
    boto3 = None


class KMSEncryption:
    """
    AWS KMS-based encryption service.
    
    Architecture:
    1. Data Encryption Key (DEK) generated by KMS
    2. DEK encrypts actual data (AES-256)
    3. Encrypted DEK stored with ciphertext
    4. KMS decrypts DEK using Customer Master Key (CMK)
    5. Decrypted DEK used to decrypt data
    
    This is "envelope encryption" - data never sent to KMS, only keys.
    """
    
    def __init__(self):
        self.kms_key_id = os.environ.get("KMS_KEY_ID")
        self.aws_region = os.environ.get("AWS_REGION", "ap-southeast-1")
        self.use_kms = KMS_AVAILABLE and self.kms_key_id
        
        if self.use_kms:
            self.kms_client = boto3.client('kms', region_name=self.aws_region)
            print(f"✓ KMS encryption ENABLED (Production) - Key: {self.kms_key_id[:20]}...")
        else:
            print("⚠️  KMS not configured - Encryption DISABLED (Development mode - plaintext storage)")
    
    def encrypt(self, plaintext: str, encryption_context: Optional[dict] = None) -> str:
        """
        Encrypt data using AWS KMS.
        
        Args:
            plaintext: Data to encrypt (e.g., email, phone)
            encryption_context: Additional authenticated data (e.g., user_id, field_name)
                               This binds ciphertext to specific context for added security
        
        Returns:
            Base64-encoded ciphertext (format: "encrypted_dek:ciphertext")
            
        Example:
            >>> kms = KMSEncryption()
            >>> encrypted = kms.encrypt("nguyen@gmail.com", {"user_id": "123", "field": "email"})
        """
        if not plaintext:
            return None
        
        if not self.use_kms:
            # Development mode: no encryption, return plaintext
            return plaintext
        
        try:
            # Use KMS to encrypt directly (for small data <4KB)
            # For larger data, use envelope encryption with GenerateDataKey
            response = self.kms_client.encrypt(
                KeyId=self.kms_key_id,
                Plaintext=plaintext.encode('utf-8'),
                EncryptionContext=encryption_context or {}
            )
            
            # Return base64-encoded ciphertext
            ciphertext_blob = response['CiphertextBlob']
            return base64.b64encode(ciphertext_blob).decode('utf-8')
            
        except ClientError as e:
            error_code = e.response['Error']['Code']
            if error_code == 'AccessDeniedException':
                raise PermissionError(
                    "Service does not have permission to use KMS key. "
                    "Check IAM role has kms:Encrypt permission."
                )
            raise RuntimeError(f"KMS encryption failed: {e}")
    
    def decrypt(self, ciphertext: str, encryption_context: Optional[dict] = None) -> str:
        """
        Decrypt data using AWS KMS.
        
        Args:
            ciphertext: Base64-encoded encrypted data
            encryption_context: Must match context used during encryption
        
        Returns:
            Decrypted plaintext string
            
        Raises:
            PermissionError: If service lacks kms:Decrypt permission
            ValueError: If encryption context doesn't match
        """
        if not ciphertext:
            return None
        
        if not self.use_kms:
            # Development mode: no decryption needed, return as-is
            return ciphertext
        
        try:
            # Decode base64 ciphertext
            ciphertext_blob = base64.b64decode(ciphertext)
            
            # Decrypt using KMS (auto-detects which key was used)
            response = self.kms_client.decrypt(
                CiphertextBlob=ciphertext_blob,
                EncryptionContext=encryption_context or {}
            )
            
            return response['Plaintext'].decode('utf-8')
            
        except ClientError as e:
            error_code = e.response['Error']['Code']
            if error_code == 'AccessDeniedException':
                raise PermissionError(
                    "Service does not have permission to decrypt data. "
                    "Check IAM role has kms:Decrypt permission."
                )
            elif error_code == 'InvalidCiphertextException':
                raise ValueError(
                    "Encryption context mismatch or data corrupted. "
                    "Context must match encryption parameters."
                )
            raise RuntimeError(f"KMS decryption failed: {e}")


# Singleton instance
_kms_instance: Optional[KMSEncryption] = None


def get_kms() -> KMSEncryption:
    """Get or create KMS encryption instance (singleton)."""
    global _kms_instance
    if _kms_instance is None:
        _kms_instance = KMSEncryption()
    return _kms_instance


def encrypt_field_kms(value: str, user_id: Optional[int] = None, field_name: Optional[str] = None) -> str:
    """
    Encrypt a database field using KMS.
    
    Args:
        value: Plain text to encrypt
        user_id: User ID for encryption context (binds ciphertext to user)
        field_name: Field name (e.g., "email", "phone") for context
    
    Returns:
        Encrypted string safe for database storage
        
    Example:
        >>> encrypted_email = encrypt_field_kms("test@example.com", user_id=123, field_name="email")
    """
    if not value:
        return None
    
    kms = get_kms()
    
    # Build encryption context for added security
    context = {}
    if user_id:
        context['user_id'] = str(user_id)
    if field_name:
        context['field'] = field_name
    
    return kms.encrypt(value, encryption_context=context if context else None)


def decrypt_field_kms(encrypted_value: str, user_id: Optional[int] = None, field_name: Optional[str] = None) -> str:
    """
    Decrypt a database field using KMS.
    
    Args:
        encrypted_value: Encrypted data from database
        user_id: User ID for encryption context (must match encryption)
        field_name: Field name for context (must match encryption)
    
    Returns:
        Decrypted plain text
        
    Example:
        >>> email = decrypt_field_kms(user._encrypted_email, user_id=user.id, field_name="email")
    """
    if not encrypted_value:
        return None
    
    kms = get_kms()
    
    # Build same encryption context
    context = {}
    if user_id:
        context['user_id'] = str(user_id)
    if field_name:
        context['field'] = field_name
    
    return kms.decrypt(encrypted_value, encryption_context=context if context else None)


# Test KMS connectivity
def test_kms_connection() -> Tuple[bool, str]:
    """
    Test KMS connection and permissions.
    
    Returns:
        (success: bool, message: str)
    """
    kms = get_kms()
    
    if not kms.use_kms:
        return False, "KMS not configured - using local encryption"
    
    try:
        # Test encrypt/decrypt cycle
        test_data = "kms_connection_test"
        encrypted = kms.encrypt(test_data)
        decrypted = kms.decrypt(encrypted)
        
        if decrypted == test_data:
            return True, f"✓ KMS connection successful (Region: {kms.aws_region})"
        else:
            return False, "✗ KMS roundtrip failed - data mismatch"
            
    except PermissionError as e:
        return False, f"✗ Permission denied: {e}"
    except Exception as e:
        return False, f"✗ KMS connection failed: {e}"


if __name__ == "__main__":
    # Quick test when run directly
    print("Testing KMS encryption...")
    success, message = test_kms_connection()
    print(message)
    
    if success:
        # Test with encryption context
        kms = get_kms()
        test_email = "test@example.com"
        
        encrypted = encrypt_field_kms(test_email, user_id=123, field_name="email")
        decrypted = decrypt_field_kms(encrypted, user_id=123, field_name="email")
        
        print(f"\nTest data: {test_email}")
        print(f"Encrypted: {encrypted[:60]}...")
        print(f"Decrypted: {decrypted}")
        print(f"Match: {decrypted == test_email}")
        
        # Test context validation (should fail with wrong context)
        try:
            wrong_decrypt = decrypt_field_kms(encrypted, user_id=999, field_name="email")
            print("⚠️  WARNING: Context validation not working!")
        except ValueError:
            print("✓ Context validation working - wrong context rejected")
